default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: simple_blog_development

test:
  <<: *default
  database: simple_blog_test

production:
  <<: *default
  database: simple_blog_production
  username: deploy
  password: <%= ENV['SIMPLE_BLOG_DATABASE_PASSWORD'] %>
